import test from "node:test";
import assert from "node:assert/strict";
import { spawn } from "node:child_process";
import { once } from "node:events";
import { access,mkdir,mkdtemp,readFile,rm,writeFile } from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import {
  CODEX_BUNDLE_IDENTIFIER,
  OPENAI_CODEX_TEAM_IDENTIFIER,
  classifyCodexAppProcesses,
  cleanRuntimeArtifacts,
  ensureRuntimeHome,
  ensureSkinCodex,
  findThemeDaemonProcesses,
  getRuntimePaths,
  isProcessAlive,
  readCommandArgument,
  readState,
  removeState,
  stableLaunchDirectory,
  terminateSkinCodexInstance,
  validateCodexSignatureOutput,
  writeState,
} from "../src/runtime.mjs";
test("运行状态原子写入并可逆清理",async(context)=>{const container=await mkdtemp(path.join(os.tmpdir(),"codex-skin-test-")),home=path.join(container,"runtime");context.after(()=>rm(container,{recursive:true,force:true}));const paths=getRuntimePaths({CODEX_SKIN_HOME:home}),state={schemaVersion:1,daemonPid:12345,theme:"makima"};await writeState(paths,state);assert.deepEqual(await readState(paths),state);assert.equal(await removeState(paths,54321),false);assert.equal(await removeState(paths,12345),true);assert.equal(await readState(paths),null);});
test("运行目录所有读写删除都要求预先存在的所有权标记",async(context)=>{const unownedHome=await mkdtemp(path.join(os.tmpdir(),"codex-skin-unowned-"));context.after(()=>rm(unownedHome,{recursive:true,force:true}));const unownedPaths=getRuntimePaths({CODEX_SKIN_HOME:unownedHome});await writeFile(unownedPaths.stateFile,"user-data\n");await assert.rejects(ensureRuntimeHome(unownedPaths),/没有皮肤所有权标记/);await assert.rejects(readState(unownedPaths),/没有皮肤所有权标记/);await assert.rejects(removeState(unownedPaths),/没有皮肤所有权标记/);await assert.rejects(cleanRuntimeArtifacts(unownedPaths),/没有皮肤所有权标记/);assert.equal(await readFile(unownedPaths.stateFile,"utf8"),"user-data\n");const container=await mkdtemp(path.join(os.tmpdir(),"codex-skin-owned-"));context.after(()=>rm(container,{recursive:true,force:true}));const ownedHome=path.join(container,"runtime"),ownedPaths=getRuntimePaths({CODEX_SKIN_HOME:ownedHome});await ensureRuntimeHome(ownedPaths);await mkdir(ownedPaths.profileDir,{recursive:true});await writeState(ownedPaths,{theme:"makima",daemonPid:1});await cleanRuntimeArtifacts(ownedPaths);await access(ownedPaths.profileDir);assert.equal(await readState(ownedPaths),null);await assert.doesNotReject(ensureRuntimeHome(ownedPaths));});
test("独立 profile 与真实 ps 风格启动参数解析",()=>{const paths=getRuntimePaths({CODEX_SKIN_HOME:"/tmp/skin-home",CODEX_SKIN_PROFILE_DIR:"/tmp/skin-profile"});assert.equal(paths.profileDir,"/tmp/skin-profile");assert.equal(readCommandArgument("ChatGPT --user-data-dir='/tmp/profile with spaces' --remote-debugging-port=9229","--user-data-dir"),"/tmp/profile with spaces");const command="/Applications/ChatGPT.app/Contents/MacOS/ChatGPT --user-data-dir=/Users/chenqi/Library/Application Support/Codex Makima Skin/Profile --remote-debugging-address=127.0.0.1 --remote-debugging-port=0";assert.equal(readCommandArgument(command,"--user-data-dir"),"/Users/chenqi/Library/Application Support/Codex Makima Skin/Profile");assert.equal(readCommandArgument(command,"--remote-debugging-address"),"127.0.0.1");assert.equal(readCommandArgument(command,"--remote-debugging-port"),"0");});
test("主题可选择独立的 Codex Skin Studio 运行目录",()=>{const makima=getRuntimePaths({}),faye=getRuntimePaths({},{runtimeDirectory:"Codex Skin Studio/Runtime/faye"});assert.match(makima.home,/Codex Skin Studio\/Runtime\/makima$/);assert.match(faye.home,/Codex Skin Studio\/Runtime\/faye$/);assert.notEqual(makima.home,faye.home);});
test("Codex Skin Studio 按主题派生运行目录和新版所有权标记",async(context)=>{const home=await mkdtemp(path.join(os.tmpdir(),"codex-studio-home-"));context.after(()=>rm(home,{recursive:true,force:true}));const paths=getRuntimePaths({HOME:home},{runtimeDirectory:"Codex Skin Studio/Runtime/moonlit-archive"});assert.equal(paths.home,path.join(home,"Library","Application Support","Codex Skin Studio","Runtime","moonlit-archive"));await ensureRuntimeHome(paths);assert.equal(await readFile(path.join(paths.home,".codex-skin-studio-owned"),"utf8"),"codex-skin-studio:v1\n");});
test("进程检查拒绝无效 PID",()=>{assert.equal(isProcessAlive(process.pid),true);assert.equal(isProcessAlive(0),false);assert.equal(isProcessAlive("invalid"),false);});
test("长期运行的子进程使用稳定目录而非可替换的 app bundle",async()=>{assert.equal(stableLaunchDirectory(),os.homedir());await access(stableLaunchDirectory());});

test("Codex 主进程按 profile 与共享 Codex home 分类",async(context)=>{const home=await mkdtemp(path.join(os.tmpdir(),"codex skin classify "));context.after(()=>rm(home,{recursive:true,force:true}));const executablePath="/Applications/ChatGPT.app/Contents/MacOS/ChatGPT",profileDir=path.join(home,"Profile With Spaces"),codexHome=path.join(home,".codex");const skinCommand=`${executablePath} --user-data-dir=${profileDir} --remote-debugging-address=127.0.0.1 --remote-debugging-port=0`,defaultCommand=executablePath,isolatedCommand=`${executablePath} --user-data-dir=/tmp/other-profile`;const result=await classifyCodexAppProcesses({executablePath},profileDir,{codexHome,processRows:[{pid:101,command:skinCommand,environmentCommand:`${skinCommand} HOME=${home} PATH=/usr/bin`},{pid:102,command:defaultCommand,environmentCommand:`${defaultCommand} HOME=${home} PATH=/usr/bin`},{pid:103,command:isolatedCommand,environmentCommand:`${isolatedCommand} HOME=${home} CODEX_HOME=/tmp/isolated-codex-home PATH=/usr/bin`},{pid:104,command:"/Applications/ChatGPT.app/Contents/Frameworks/Codex Helper --type=renderer",environmentCommand:""}]});assert.deepEqual(result.profileProcesses.map(({pid})=>pid),[101]);assert.deepEqual(result.otherProcesses.map(({pid})=>pid),[102,103]);assert.deepEqual(result.otherSharedCodexHomeProcesses.map(({pid})=>pid),[102]);assert.equal(result.profileProcesses[0].remoteDebuggingPort,0);assert.equal(result.otherSharedCodexHomeProcesses[0].remoteDebuggingPort,null);});

test("daemon 扫描只接受 Node 运行的匹配 profile",async(context)=>{const home=await mkdtemp(path.join(os.tmpdir(),"codex daemon profile "));context.after(()=>rm(home,{recursive:true,force:true}));const profileDir=path.join(home,"Profile With Spaces"),rows=[{pid:201,command:`/opt/homebrew/bin/node /old/project path/bin/codex-skin.mjs daemon --port 52975 --app-pid 96283 --profile ${profileDir}`},{pid:202,command:`/opt/homebrew/bin/node /new/path/bin/codex-skin.mjs daemon --port 52976 --profile /tmp/another-profile`},{pid:203,command:`/opt/homebrew/bin/node /old/project/bin/other.mjs daemon --port 52977 --profile ${profileDir}`},{pid:204,command:`/bin/zsh codex-skin.mjs daemon --port 52978 --profile ${profileDir}`},{pid:205,executableName:"node",command:`/Applications/Codex Pro.app/Contents/Resources/runtime/node /Applications/Codex Pro.app/Contents/Resources/runtime/bin/codex-skin.mjs daemon --port 52979 --profile ${profileDir}`}],matches=await findThemeDaemonProcesses(profileDir,{processRows:rows});assert.deepEqual(matches.map(({pid})=>pid),[201,205]);assert.equal(matches[0].port,52975);assert.equal(matches[0].appPid,96283);assert.equal(matches[1].port,52979);});

test("daemon 扫描可识别真实 Node 进程路径中的空格",async(context)=>{const home=await mkdtemp(path.join(os.tmpdir(),"codex daemon live "));context.after(()=>rm(home,{recursive:true,force:true}));const profileDir=path.join(home,"Profile With Spaces"),child=spawn(process.execPath,["-e","setInterval(()=>{},1000)","codex-skin.mjs","daemon","--port","52980","--profile",profileDir],{stdio:"ignore"});await once(child,"spawn");context.after(()=>{if(isProcessAlive(child.pid))process.kill(child.pid,"SIGTERM");});const matches=await findThemeDaemonProcesses(profileDir);assert.equal(matches.some(({pid,port})=>pid===child.pid&&port===52980),true);});

test("Codex 签名必须属于当前实测 OpenAI Team",()=>{const valid=`Identifier=${CODEX_BUNDLE_IDENTIFIER}\nTeamIdentifier=${OPENAI_CODEX_TEAM_IDENTIFIER}\n`;assert.deepEqual(validateCodexSignatureOutput(valid),{valid:true,identifier:CODEX_BUNDLE_IDENTIFIER,teamIdentifier:OPENAI_CODEX_TEAM_IDENTIFIER});assert.throws(()=>validateCodexSignatureOutput(`Identifier=${CODEX_BUNDLE_IDENTIFIER}\nTeamIdentifier=OTHERTEAM\n`),/TeamIdentifier 不匹配/);assert.throws(()=>validateCodexSignatureOutput(`Identifier=com.example.fake\nTeamIdentifier=${OPENAI_CODEX_TEAM_IDENTIFIER}\n`),/签名标识不匹配/);});

test("只终止调用方拥有的新实例并等待退出",async(context)=>{const child=spawn(process.execPath,["-e","setInterval(()=>{},1000)"],{stdio:"ignore"});await once(child,"spawn");context.after(()=>{if(isProcessAlive(child.pid))process.kill(child.pid,"SIGTERM");});assert.equal(await terminateSkinCodexInstance({appPid:child.pid,ownedByCaller:false},500),false);assert.equal(isProcessAlive(child.pid),true);assert.equal(await terminateSkinCodexInstance({appPid:child.pid,ownedByCaller:true},3000),true);assert.equal(isProcessAlive(child.pid),false);});

test("新实例在 CDP 启动失败时自动回收并报告 PID",async(context)=>{const container=await mkdtemp(path.join(os.tmpdir(),"codex-skin-startup-failure-")),home=path.join(container,"runtime");context.after(()=>rm(container,{recursive:true,force:true}));const paths=getRuntimePaths({CODEX_SKIN_HOME:home}),app={executablePath:process.execPath};let failure;await assert.rejects(ensureSkinCodex(app,paths),error=>{failure=error;return /CDP 就绪前退出/.test(error.message);});assert.equal(Number.isInteger(failure.appPid),true);assert.equal(failure.cleanupCompleted,true);assert.equal(isProcessAlive(failure.appPid),false);});
