const REQUEST_TIMEOUT=5_000;
const LOOPBACK=new Set(["127.0.0.1","localhost","::1"]);
export function isCodexPageTarget(target,expectedPort=null){if(target?.type!=="page"||target.url!=="app://-/index.html"||typeof target.webSocketDebuggerUrl!=="string")return false;try{const url=new URL(target.webSocketDebuggerUrl);return url.protocol==="ws:"&&LOOPBACK.has(url.hostname)&&(expectedPort===null||Number(url.port)===Number(expectedPort))&&url.pathname.startsWith("/devtools/page/");}catch{return false;}}
export async function fetchCdpJson(port,pathname,{timeoutMs=2_000}={}){const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),timeoutMs);try{const response=await fetch(`http://127.0.0.1:${port}${pathname}`,{signal:controller.signal,cache:"no-store"});if(!response.ok)throw new Error(`CDP HTTP ${response.status}: ${pathname}`);return await response.json();}finally{clearTimeout(timeout);}}
export async function listCdpTargets(port,options={}){return(await fetchCdpJson(port,"/json/list",options)).filter((target)=>isCodexPageTarget(target,port));}
export async function waitForCdp(port,{timeoutMs=25_000,intervalMs=250}={}){const deadline=Date.now()+timeoutMs;let lastError;while(Date.now()<deadline){try{await fetchCdpJson(port,"/json/version",{timeoutMs:Math.min(intervalMs*2,1_000)});return;}catch(error){lastError=error;await new Promise((resolve)=>setTimeout(resolve,intervalMs));}}throw new Error(`等待 Codex 调试端口 ${port} 超时${lastError?`：${lastError.message}`:""}`);}
export class CdpClient{
  #socket;#sequence=0;#pending=new Map();#closed=false;
  static async connect(url,{timeoutMs=REQUEST_TIMEOUT,WebSocketImpl=globalThis.WebSocket}={}){if(!WebSocketImpl)throw new Error("当前 Node.js 不提供 WebSocket；请使用 Node.js 22 或更高版本");const socket=new WebSocketImpl(url);await new Promise((resolve,reject)=>{const timeout=setTimeout(()=>reject(new Error(`连接 CDP WebSocket 超时：${url}`)),timeoutMs);const done=(callback)=>()=>{clearTimeout(timeout);callback();};socket.addEventListener("open",done(resolve),{once:true});socket.addEventListener("error",done(()=>reject(new Error(`无法连接 CDP WebSocket：${url}`))),{once:true});});return new CdpClient(socket);}
  constructor(socket){this.#socket=socket;socket.addEventListener("message",(event)=>{const message=JSON.parse(String(event.data)),request=message.id?this.#pending.get(message.id):null;if(!request)return;this.#pending.delete(message.id);clearTimeout(request.timeout);if(message.error)request.reject(new Error(`${message.error.message}${message.error.data?`：${message.error.data}`:""}`));else request.resolve(message.result);});const closed=()=>{if(this.#closed)return;this.#closed=true;for(const request of this.#pending.values()){clearTimeout(request.timeout);request.reject(new Error("CDP WebSocket 已关闭"));}this.#pending.clear();};socket.addEventListener("close",closed,{once:true});socket.addEventListener("error",closed,{once:true});}
  get closed(){return this.#closed;}
  call(method,params={},{timeoutMs=REQUEST_TIMEOUT}={}){if(this.#closed)return Promise.reject(new Error("CDP WebSocket 已关闭"));const id=++this.#sequence;return new Promise((resolve,reject)=>{const timeout=setTimeout(()=>{this.#pending.delete(id);reject(new Error(`CDP 调用超时：${method}`));},timeoutMs);this.#pending.set(id,{resolve,reject,timeout});this.#socket.send(JSON.stringify({id,method,params}));});}
  close(){if(!this.#closed)this.#socket.close();}
}
