import crypto from "node:crypto";
import {execFile,spawn} from "node:child_process";
import {once} from "node:events";
import {createReadStream} from "node:fs";
import {access,mkdir,open,readFile,realpath,rename,rm,writeFile} from "node:fs/promises";
import net from "node:net";
import os from "node:os";
import path from "node:path";
import {promisify} from "node:util";
import {fetchCdpJson} from "./cdp.mjs";
const execFileAsync=promisify(execFile);
export const CODEX_BUNDLE_IDENTIFIER="com.openai.codex";
export const OPENAI_CODEX_TEAM_IDENTIFIER="2DC432GLL2";
const RUNTIME_MARKER_FILE=".codex-skin-studio-owned";
const RUNTIME_MARKER_VALUE="codex-skin-studio:v1\n";
export function stableLaunchDirectory(){return os.homedir();}
export function getRuntimePaths(env=process.env,{runtimeDirectory="Codex Skin Studio/Runtime/makima"}={}){const userHome=env.HOME||os.homedir(),home=env.CODEX_SKIN_HOME||path.join(userHome,"Library","Application Support",runtimeDirectory);return{home,profileDir:env.CODEX_SKIN_PROFILE_DIR||path.join(home,"Profile"),stateFile:path.join(home,"state.json"),logFile:path.join(home,"theme.log"),appLogFile:path.join(home,"codex.log")};}
async function assertRuntimeOwnership(paths,{allowMissingHome=false}={}){const marker=path.join(paths.home,RUNTIME_MARKER_FILE);let value;try{value=await readFile(marker,"utf8");}catch(error){if(error.code!=="ENOENT")throw error;if(allowMissingHome){try{await access(paths.home);}catch(homeError){if(homeError.code==="ENOENT")return false;throw homeError;}}throw new Error(`拒绝访问没有皮肤所有权标记的运行目录：${paths.home}`);}if(value!==RUNTIME_MARKER_VALUE)throw new Error(`皮肤运行目录所有权标记不匹配：${marker}`);return true;}
export async function ensureRuntimeHome(paths){const created=await mkdir(paths.home,{recursive:true,mode:0o700});if(created===undefined){await assertRuntimeOwnership(paths);return;}const marker=path.join(paths.home,RUNTIME_MARKER_FILE);try{await writeFile(marker,RUNTIME_MARKER_VALUE,{mode:0o600,flag:"wx"});}catch(error){if(error.code!=="EEXIST")throw error;await assertRuntimeOwnership(paths);}}
export async function readState(paths){if(!await assertRuntimeOwnership(paths,{allowMissingHome:true}))return null;try{return JSON.parse(await readFile(paths.stateFile,"utf8"));}catch(error){if(error.code==="ENOENT"||error instanceof SyntaxError)return null;throw error;}}
export async function writeState(paths,state){await ensureRuntimeHome(paths);const temporary=path.join(paths.home,`.state-${process.pid}-${Date.now()}.json`);await writeFile(temporary,`${JSON.stringify(state,null,2)}\n`,{mode:0o600});await rename(temporary,paths.stateFile);}
export async function removeState(paths,expectedPid=null){if(!await assertRuntimeOwnership(paths,{allowMissingHome:true}))return false;if(expectedPid!==null&&(await readState(paths))?.daemonPid!==expectedPid)return false;await rm(paths.stateFile,{force:true});return true;}
export async function cleanRuntimeArtifacts(paths){if(!await assertRuntimeOwnership(paths,{allowMissingHome:true}))return false;await rm(paths.stateFile,{force:true});await rm(paths.logFile,{force:true});await rm(paths.appLogFile,{force:true});return true;}
export async function resolveCodexApp(override=process.env.CODEX_APP_PATH){const candidates=[override,"/Applications/ChatGPT.app","/Applications/Codex.app",path.join(os.homedir(),"Applications","ChatGPT.app"),path.join(os.homedir(),"Applications","Codex.app")].filter(Boolean);for(const appPath of candidates){try{const plist=path.join(appPath,"Contents","Info.plist"),bundleId=await plistValue(plist,"CFBundleIdentifier");if(bundleId!==CODEX_BUNDLE_IDENTIFIER)continue;const executableName=await plistValue(plist,"CFBundleExecutable"),executablePath=path.join(appPath,"Contents","MacOS",executableName);await access(executablePath);return{appPath,bundleId,executableName,executablePath,version:await plistValue(plist,"CFBundleShortVersionString"),build:await plistValue(plist,"CFBundleVersion")};}catch{}}throw new Error(`未找到 Bundle ID 为 ${CODEX_BUNDLE_IDENTIFIER} 的 Codex 桌面应用；可用 CODEX_APP_PATH 指定 .app 路径`);}
async function plistValue(plist,key){const{stdout}=await execFileAsync("/usr/libexec/PlistBuddy",["-c",`Print :${key}`,plist]);return stdout.trim();}
export async function sha256File(filePath){return new Promise((resolve,reject)=>{const hash=crypto.createHash("sha256"),stream=createReadStream(filePath);stream.on("error",reject);stream.on("data",(chunk)=>hash.update(chunk));stream.on("end",()=>resolve(hash.digest("hex")));});}
export async function fingerprintApp(app){const asar=path.join(app.appPath,"Contents","Resources","app.asar"),[executableSha256,appAsarSha256]=await Promise.all([sha256File(app.executablePath),sha256File(asar)]);return{executableSha256,appAsarSha256,capturedAt:new Date().toISOString()};}
export function validateCodexSignatureOutput(output){const identifier=output.match(/^Identifier=(.+)$/m)?.[1]?.trim()||null,teamIdentifier=output.match(/^TeamIdentifier=(.+)$/m)?.[1]?.trim()||null;if(identifier!==CODEX_BUNDLE_IDENTIFIER)throw new Error(`Codex 签名标识不匹配：期望 ${CODEX_BUNDLE_IDENTIFIER}，实际 ${identifier||"未报告"}`);if(teamIdentifier!==OPENAI_CODEX_TEAM_IDENTIFIER)throw new Error(`Codex 签名 TeamIdentifier 不匹配：期望 ${OPENAI_CODEX_TEAM_IDENTIFIER}，实际 ${teamIdentifier||"未报告"}`);return{valid:true,identifier,teamIdentifier};}
export async function verifyCodeSignature(appPath){const requirement=`identifier "${CODEX_BUNDLE_IDENTIFIER}" and anchor apple generic and certificate leaf[subject.OU] = "${OPENAI_CODEX_TEAM_IDENTIFIER}"`;await execFileAsync("/usr/bin/codesign",["--verify","--deep","--strict",`-R=${requirement}`,appPath]);const{stderr}=await execFileAsync("/usr/bin/codesign",["-dv","--verbose=4",appPath]);return validateCodexSignatureOutput(stderr);}
export async function findRunningAppPids(executablePath){const{stdout}=await execFileAsync("/bin/ps",["-axo","pid=,command="]);return stdout.split("\n").map((line)=>line.trim()).map((line)=>{const match=line.match(/^(\d+)\s+(.+)$/);return match?{pid:Number(match[1]),command:match[2]}:null;}).filter(Boolean).filter(({command})=>command===executablePath||command.startsWith(`${executablePath} `)).map(({pid})=>pid);}
export function isProcessAlive(pid){if(!Number.isInteger(Number(pid))||Number(pid)<=0)return false;try{process.kill(Number(pid),0);return true;}catch{return false;}}
export async function isThemeDaemonProcess(pid,entrypoint){if(!isProcessAlive(pid))return false;try{const{stdout}=await execFileAsync("/bin/ps",["-p",String(pid),"-o","command="]),command=stdout.trim();return command.includes(entrypoint)&&(/(^|\s)daemon(\s|$)/.test(command)||(/(^|\s)start(\s|$)/.test(command)&&/(^|\s)--foreground(\s|$)/.test(command)));}catch{return false;}}
export async function findFreePort(){return new Promise((resolve,reject)=>{const server=net.createServer();server.unref();server.on("error",reject);server.listen({host:"127.0.0.1",port:0},()=>{const address=server.address(),port=typeof address==="object"?address.port:null;server.close((error)=>error?reject(error):resolve(port));});});}
export function launchCodex(app,port){const child=spawn(app.executablePath,["--remote-debugging-address=127.0.0.1",`--remote-debugging-port=${port}`],{cwd:stableLaunchDirectory(),detached:true,stdio:"ignore",env:process.env});child.unref();return child.pid;}
export async function terminateProcessesGracefully(pids,timeoutMs=12_000){const targets=pids.filter(isProcessAlive);for(const pid of targets)process.kill(pid,"SIGTERM");const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){if(targets.every((pid)=>!isProcessAlive(pid)))return;await new Promise((resolve)=>setTimeout(resolve,150));}throw new Error(`Codex 进程未在限定时间内退出：${targets.filter(isProcessAlive).join(", ")}；为避免数据风险，未使用 SIGKILL`);}

export function readCommandArgument(command,name){if(typeof command!=="string"||typeof name!=="string")return null;const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),match=new RegExp(`(?:^|\\s)${escaped}(?:=|\\s+)`).exec(command);if(!match)return null;const remainder=command.slice(match.index+match[0].length);if(remainder.length===0)return null;const quote=remainder[0];if(quote==='"'||quote==="'"){for(let index=1;index<remainder.length;index+=1)if(remainder[index]===quote&&remainder[index-1]!=="\\")return remainder.slice(1,index);return remainder.slice(1)||null;}const nextOption=remainder.search(/\s+--[A-Za-z0-9][A-Za-z0-9-]*(?=(?:=|\s|$))/),value=(nextOption===-1?remainder:remainder.slice(0,nextOption)).trim();return value||null;}

export async function classifyCodexAppProcesses(app,profileDir,{codexHome=path.join(os.homedir(),".codex"),processRows=null}={}){const expectedProfile=await canonicalize(profileDir),expectedCodexHome=await canonicalize(codexHome),rows=processRows??await readCodexMainProcessRows(app.executablePath),allProcesses=[];for(const row of rows){if(!isMainExecutableCommand(row.command,app.executablePath))continue;const rawProfile=readCommandArgument(row.command,"--user-data-dir"),resolvedProfile=rawProfile?await canonicalize(rawProfile):null,environmentCommand=row.environmentCommand??row.command,processHome=readEnvironmentValue(environmentCommand,"HOME")||os.homedir(),rawCodexHome=readEnvironmentValue(environmentCommand,"CODEX_HOME")||path.join(processHome,".codex"),resolvedCodexHome=await canonicalize(rawCodexHome),rawPort=readCommandArgument(row.command,"--remote-debugging-port"),numericPort=rawPort===null?null:Number(rawPort),remoteDebuggingPort=Number.isInteger(numericPort)&&numericPort>=0&&numericPort<=65535?numericPort:null,usesProfile=resolvedProfile===expectedProfile,sharesCodexHome=resolvedCodexHome===expectedCodexHome;allProcesses.push({pid:Number(row.pid),command:row.command,profileDir:resolvedProfile,remoteDebuggingPort,codexHome:resolvedCodexHome,usesProfile,sharesCodexHome});}return{allProcesses,profileProcesses:allProcesses.filter((process)=>process.usesProfile),otherProcesses:allProcesses.filter((process)=>!process.usesProfile),otherSharedCodexHomeProcesses:allProcesses.filter((process)=>!process.usesProfile&&process.sharesCodexHome)};}

export async function findSkinAppProcesses(app,profileDir){return(await classifyCodexAppProcesses(app,profileDir)).profileProcesses.map(({pid,command})=>({pid,command}));}

export async function findThemeDaemonProcesses(profileDir,{processRows=null}={}){const expectedProfile=await canonicalize(profileDir),rows=processRows??await readProcessTable(),matches=[];for(const row of rows){const command=row.command.trim(),scriptIndex=command.indexOf("codex-skin.mjs"),daemonMatch=/(?:^|\s)daemon(?:\s|$)/.exec(command);if(scriptIndex===-1||!daemonMatch||daemonMatch.index<scriptIndex)continue;const executableName=row.executableName??(processRows===null?await readProcessExecutableName(row.pid):path.basename(command.split(/\s+/,1)[0]));if(executableName!=="node")continue;const rawProfile=readCommandArgument(command,"--profile");if(!rawProfile||(await canonicalize(rawProfile))!==expectedProfile)continue;matches.push({pid:Number(row.pid),command,profileDir:expectedProfile,port:parsePositiveInteger(readCommandArgument(command,"--port"),65535),appPid:parsePositiveInteger(readCommandArgument(command,"--app-pid"))});}return matches;}

export async function ensureSkinCodex(app,paths,logger=()=>{}){await ensureRuntimeHome(paths);await mkdir(paths.profileDir,{recursive:true,mode:0o700});const profileDir=await realpath(paths.profileDir),activePortFile=path.join(profileDir,"DevToolsActivePort"),existing=await findSkinAppProcesses(app,profileDir);if(existing.length>0){const configuredPort=Number(readCommandArgument(existing[0].command,"--remote-debugging-port")),port=Number.isInteger(configuredPort)&&configuredPort>0&&configuredPort<=65535?configuredPort:await waitForDevToolsPort(activePortFile,existing[0].pid,8_000);await fetchCdpJson(port,"/json/version",{timeoutMs:5_000});return{appPid:existing[0].pid,port,profileDir,reused:true,ownedByCaller:false};}await rm(activePortFile,{force:true});const logHandle=await open(paths.appLogFile,"a",0o600);let child;try{child=spawn(app.executablePath,[`--user-data-dir=${profileDir}`,"--remote-debugging-address=127.0.0.1","--remote-debugging-port=0"],{cwd:stableLaunchDirectory(),detached:true,env:{...process.env,CODEX_ELECTRON_USER_DATA_PATH:profileDir},stdio:["ignore",logHandle.fd,logHandle.fd]});await once(child,"spawn");child.unref();}finally{await logHandle.close();}const instance={appPid:child.pid,profileDir,reused:false,ownedByCaller:true};logger(`已启动隔离皮肤实例，PID ${child.pid}`);try{const port=await waitForDevToolsPort(activePortFile,child.pid,20_000);await fetchCdpJson(port,"/json/version",{timeoutMs:5_000});return{...instance,port};}catch(error){const startupError=error instanceof Error?error:new Error(String(error));startupError.appPid=child.pid;try{await terminateSkinCodexInstance(instance);startupError.cleanupCompleted=true;}catch(cleanupError){startupError.cleanupCompleted=false;startupError.cleanupError=cleanupError;startupError.message+=`；回收启动失败实例时出错：${cleanupError.message}`;}throw startupError;}}

export async function terminateSkinCodexInstance(instance,timeoutMs=12_000){if(!instance?.ownedByCaller||!Number.isInteger(Number(instance.appPid))||Number(instance.appPid)<=0)return false;await terminateProcessesGracefully([Number(instance.appPid)],timeoutMs);return true;}

async function waitForDevToolsPort(activePortFile,pid,timeoutMs){const deadline=Date.now()+timeoutMs;while(Date.now()<deadline){if(!isProcessAlive(pid))throw new Error(`Codex 进程 ${pid} 在 CDP 就绪前退出`);try{const port=Number((await readFile(activePortFile,"utf8")).split(/\r?\n/,1)[0]);if(Number.isInteger(port)&&port>0&&port<=65535)return port;}catch{}await new Promise((resolve)=>setTimeout(resolve,150));}throw new Error(`等待 CDP 端口超时：${activePortFile}`);}

async function readProcessTable(){const{stdout}=await execFileAsync("/bin/ps",["-axww","-o","pid=,command="]);return parseProcessTable(stdout);}
async function readProcessExecutableName(pid){try{const{stdout}=await execFileAsync("/bin/ps",["-p",String(pid),"-o","ucomm="]);return stdout.trim()||null;}catch{return null;}}
async function readCodexMainProcessRows(executablePath){const rows=(await readProcessTable()).filter((row)=>isMainExecutableCommand(row.command,executablePath));return Promise.all(rows.map(async(row)=>{try{const{stdout}=await execFileAsync("/bin/ps",["eww","-p",String(row.pid),"-o","command="]);return{...row,environmentCommand:stdout.trim()};}catch{return{...row,environmentCommand:row.command};}}));}
function parseProcessTable(output){return output.split("\n").map((line)=>line.trim().match(/^(\d+)\s+(.+)$/)).filter(Boolean).map((match)=>({pid:Number(match[1]),command:match[2]}));}
function isMainExecutableCommand(command,executablePath){return command===executablePath||command.startsWith(`${executablePath} `);}
function readEnvironmentValue(command,name){const escaped=name.replace(/[.*+?^${}()|[\]\\]/g,"\\$&"),matches=[...command.matchAll(new RegExp(`(?:^|\\s)${escaped}=`,"g"))],match=matches.at(-1);if(!match)return null;const remainder=command.slice(match.index+match[0].length),nextVariable=remainder.search(/\s+[A-Za-z_][A-Za-z0-9_]*=/),value=(nextVariable===-1?remainder:remainder.slice(0,nextVariable)).trim();return value.replace(/^(['"])(.*)\1$/,"$2")||null;}
function parsePositiveInteger(value,maximum=Number.MAX_SAFE_INTEGER){const parsed=Number(value);return Number.isInteger(parsed)&&parsed>0&&parsed<=maximum?parsed:null;}
async function canonicalize(value){try{return await realpath(value);}catch{return path.resolve(value);}}
